version: '3'
services:
  dev:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: yarn build
    command: yarn global add server
    command: server -s build
    command: npm start
    ports:
      - 3000:3000